controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix: /shortlink-api/{_locale}
    requirements:
        _locale: ru
    defaults:
        _locale: ru

shortlink_redirect:
    path: /shortlink-api/{shortLink}
    controller: App\Controller\ShortLinkController::getOriginalLink
    methods: [GET]