controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: ru
    defaults:
        _locale: ru

shortlink_redirect:
    path: /{shortLink}
    controller: App\Controller\ShortLinkController::getOriginalLink
    methods: [GET]