parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/'
    App\EventSubscriber\LocaleSubscriber:
        arguments:
            $defaultLocale: 'ru'
        tags:
            - { name: kernel.event_subscriber }